import { ABeeZee } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const abeeZee = ABeeZee({
  subsets: ["latin"],
  weight: "400", 
  style: "normal",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={abeeZee.className}>
        {children}
      </body>
    </html>
  );
}
